//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Products()
        {
            this.tb_ProductDetail = new HashSet<tb_ProductDetail>();
            this.tb_ProductImage = new HashSet<tb_ProductImage>();
        }
    
        public int ProductsId { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifeby { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsFeature { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Screensize { get; set; }
        public string CPUspeed { get; set; }
        public string OperatingSystem { get; set; }
        public string GPUspeed { get; set; }
        public string MobileNetwork { get; set; }
        public string Sim { get; set; }
        public string Wifi { get; set; }
        public string GPS { get; set; }
        public string Bluetooth { get; set; }
        public string Connector { get; set; }
        public string Headphonejack { get; set; }
        public string BatteryType { get; set; }
        public string ChargingSupport { get; set; }
        public string BatteryTechnology { get; set; }
        public byte[] Image { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string Screen { get; set; }
        public Nullable<int> BatteryCapacity { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductCompanyId { get; set; }
    
        public virtual tb_ProductCategory tb_ProductCategory { get; set; }
        public virtual tb_ProductCompany tb_ProductCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductDetail> tb_ProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductImage> tb_ProductImage { get; set; }
    }
}
