//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tb_Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Store()
        {
            this.tb_Staff = new HashSet<tb_Staff>();
            this.tb_Warehouse = new HashSet<tb_Warehouse>();
        }
    
        public int StoreId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifiedby { get; set; }
        public string Alias { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string Location { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public Nullable<bool> IsStatus { get; set; }
        [Required(ErrorMessage = "Tỉnh / thành  không được để trống")]
        public Nullable<int> idProvinces { get; set; }
        [Required(ErrorMessage = "Quận / huyện không được để trống")]
        public Nullable<int> idDistricts { get; set; }
        [Required(ErrorMessage = "Phường / xã không được để trống")]
        public Nullable<int> idWards { get; set; }
    
        public virtual Districts Districts { get; set; }
        public virtual Provinces Provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Staff> tb_Staff { get; set; }
        public virtual Wards Wards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Warehouse> tb_Warehouse { get; set; }
    }
}
