//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTokens
    {
        public int UserId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual tb_Staff tb_Staff { get; set; }
    }
}
